export const titles: string[] = [
  'Spaghetti alla Carbonara',
  'Risotto ai Funghi Porcini',
  'Pollo al Limone con Patate',
  'Spaghetti',
  'Spaghe',
  'Tiramisù Classico con Caffè',
  'Insalata Caprese Fresca',
  'Salmone alla Griglia con Erbe Aromatiche',
  'Penne all\'Arrabbiata Piccante',
  'Crostata di Frutta Estiva',
  'Zuppa di Pomodoro con Basilico',
  'Lasagne al Forno con Besciamella',
  'Gnocchi al Pesto Genovese',
  'Risotto al Nero di Seppia con Gamberi',
  'Pizza Margherita con Pomodoro e Mozzarella',
  'Tagliatelle alla Bolognese',
  'Insalata di Pollo con Avocado e Lattuga',
  'Cannelloni Ripieni di Ricotta e Spinaci',
  'Frittata con Funghi e Formaggio',
  'Arrosto di Maiale con Salsa di Mele',
  'Spaghetti Aglio, Olio e Peperoncino',
  'Pesce al Forno con Patate e Limone',
  'Ravioli di Zucca con Burro e Salvia',
  'Quiche Lorraine con Pancetta e Formaggio',
  'Risotto al Prosecco con Gamberetti',
  'Melanzane Parmigiana',
  'Cappellacci di Zucca con Burro e Salvia',
  'Maiale alla Senape con Patate Arrosto',
  'Focaccia con Pomodoro e Rosmarino',
  'Riso al Curry con Verdure',
  'Polpette di Carne in Salsa di Pomodoro',
  'Farfalle al Salmone Affumicato',
  'Insalata Greca con Olive e Feta',
  'Torta di Mele e Cannella',
  'Couscous con Verdure Grigliate',
  'Pollo Tikka Masala con Riso Basmati',
  'Bruschette con Pomodoro e Basilico',
  'Pasta alla Norma con Melanzane e Pomodoro',
  'Quinoa con Avocado e Salmone Fresco',
  'Ossobuco con Risotto alla Milanese',
  'Crostini con Crema di Formaggio e Pomodoro',
  'Penne all\'Arrabbiata con Olive Nere',
  'Galette di Grano Saraceno con Funghi e Formaggio',
  'Risotto al Nero di Seppia con Calamari',
  'Frittata di Patate e Cipolla',
  'Sformato di Broccoli con Besciamella',
  'Pollo alla Cacciatora con Pomodoro e Olive',
  'Pasta al Limone con Gamberi',
  'Parmigiana di Zucchine',
  'Caponata Siciliana',
  'Filetto di Salmone alla Griglia con Salsa al Limone',
  'Risotto alla Zucca con Amaranto e Taleggio',
  'Braciola di Maiale alla Griglia',
  'Cannelloni Ripieni di Carne e Besciamella',
  'Insalata di Riso con Uova Sode e Piselli',
  'Spaghetti alle Vongole con Aglio e Prezzemolo',
  'Risotto con Funghi Porcini e Tartufo',
  'Pizza Quattro Stagioni',
  'Tagliatelle con Sugo di Pomodoro Fresco',
  'Melanzane Grigliate con Salsa Tahini',
  'Pollo al Pepe Nero con Patate Arrosto',
  'Tiramisù alle Fragole',
  'Ravioli al Nero di Seppia con Ricotta e Spinaci',
  'Pasta al Pesto di Pistacchi',
  'Involtini di Melanzane alla Parmigiana',
  'Couscous con Ceci e Verdure',
  'Frittata di Zucchine e Formaggio',
  'Pasta alla Carbonara con Guanciale',
  'Paprika Chicken con Riso Basmati',
  'Insalata di Quinoa con Avocado e Pomodori Ciliegia',
  'Crostata di Frutti di Bosco',
  'Orecchiette con Cime di Rapa e Salsiccia',
  'Torta di Cioccolato e Nocciole',
  'Gnocchi di Patate con Burro e Salvia',
  'Pollo alle Mandorle con Riso Jasmine',
  'Pasta con Salsa di Pomodoro e Basilico',
  'Torta di Mele e Noci',
  'Frittelle di Zucchine',
  'Pasta alle Olive e Capperi',
  'Insalata di Mare con Gamberi e Calamari',
  'Risotto al Limone con Zucchine Grigliate',
  'Salmone Gravlax con Salsa di Senape e Miele',
  'Caponata di Melanzane e Peperoni',
  'Pappardelle al Ragù di Cinghiale',
  'Crostini con Crema di Funghi Porcini',
  'Pollo al Curry Thai con Latte di Cocco',
  'Lasagne alla Bolognese',
  'Bruschette con Crema di Avocado e Pomodoro',
  'Risotto con Asparagi e Formaggio Asiago',
  'Cotoletta di Pollo alla Milanese',
  'Pasta alle Melanzane e Ricotta Salata',
  'Torta Tiramisù al Cioccolato Bianco',
  'Frittelle di Ricotta con Miele',
  'Risotto al Nero di Seppia con Calamaretti',
];

export const suggestedSearchQta: number = 20;